package com.evgo.slot;

import com.evgo.station.Station;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * JPA entity representing a bookable time slot at a charging station.
 *
 * <p>Maps to the {@code slots} table. Each row is a specific date + time window
 * at a station. Slots are generated by the admin when setting up or updating a station.
 *
 * <p>Slot status lifecycle:
 * <pre>
 *   AVAILABLE   → RESERVED    (booking created, payment pending)
 *   AVAILABLE   → UNAVAILABLE (admin marks slot unavailable)
 *   RESERVED    → BOOKED      (payment confirmed)
 *   RESERVED    → AVAILABLE   (payment failed or timeout)
 *   BOOKED      → AVAILABLE   (booking cancelled or completed)
 *   UNAVAILABLE → AVAILABLE   (admin re-enables slot)
 * </pre>
 *
 * Requirements: 12.1, 12.2, 12.3, 12.4
 */
@Entity
@Table(
    name = "slots",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_slot",
        columnNames = {"station_id", "slot_date", "start_time"}
    )
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Slot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "station_id", nullable = false)
    private Station station;

    @Column(name = "slot_date", nullable = false)
    private LocalDate slotDate;

    @Column(name = "start_time", nullable = false)
    private LocalTime startTime;

    @Column(name = "end_time", nullable = false)
    private LocalTime endTime;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private SlotStatus status = SlotStatus.AVAILABLE;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
